import { EngineConfigurationOption, NameText, UnitText } from 'sonolus-core'

export const optionsDefinition = {
    autoplay: {
        name: NameText.AutoPlay,
        scope: 'Deemo',
        standard: true,
        type: 'toggle',
        def: 0,
    },
    speed: {
        name: NameText.LevelSpeed,
        standard: true,
        advanced: true,
        type: 'slider',
        def: 1,
        min: 0.5,
        max: 2,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    hidden: {
        name: NameText.Hidden,
        standard: true,
        advanced: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: UnitText.Percentage,
    },
    noteSpeed: {
        name: NameText.NoteSpeed,
        scope: 'Deemo',
        type: 'slider',
        def: 6,
        min: 1,
        max: 12,
        step: 0.1,
    },
    mirror: {
        name: NameText.MirrorLevel,
        type: 'toggle',
        def: 0,
    },
    sfxEnabled: {
        name: NameText.SFX,
        scope: 'Deemo',
        type: 'toggle',
        def: 1,
    },
    autoSFX: {
        name: NameText.AutoSFX,
        scope: 'Deemo',
        type: 'toggle',
        def: 0,
    },
    noteEffectEnabled: {
        name: NameText.NoteEffect,
        scope: 'Deemo',
        type: 'toggle',
        def: 1,
    },
    judgmentLineEffectEnabled: {
        name: NameText.JudgmentLineEffect,
        scope: 'Deemo',
        type: 'toggle',
        def: 1,
    },
    stageCover: {
        name: NameText.VerticalStageCover,
        scope: 'Deemo',
        advanced: true,
        type: 'slider',
        def: 0,
        min: 0,
        max: 1,
        step: 0.05,
        unit: UnitText.Percentage,
    },
} as const satisfies Record<string, EngineConfigurationOption>
